# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Project < Formula
  desc "TUI project scaffolder - create full-stack apps from your terminal"
  homepage "https://github.com/JadenB9/projectmaker"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.5.2/project_0.5.2_darwin_amd64.tar.gz"
      sha256 "68dc18cbb832caa58d58508380ff9bf000880565cc721be12b5c2d010be1f2b9"

      define_method(:install) do
        bin.install "project"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.5.2/project_0.5.2_darwin_arm64.tar.gz"
      sha256 "09bc5e359091cf9e497cd8c901b63ef268b626b9f865cc5d5050d58a4c87964e"

      define_method(:install) do
        bin.install "project"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.5.2/project_0.5.2_linux_amd64.tar.gz"
      sha256 "26da41a7bd08bb8dc1c3fb310b6cc8d5f79701d22f58e5c2daea60303c39adbd"
      define_method(:install) do
        bin.install "project"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.5.2/project_0.5.2_linux_arm64.tar.gz"
      sha256 "3d6cfafaf9168cf1949c5531915c338fa655f84758a6fe8612839de89d432259"
      define_method(:install) do
        bin.install "project"
      end
    end
  end
end
