# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Project < Formula
  desc "TUI project scaffolder - create full-stack apps from your terminal"
  homepage "https://github.com/JadenB9/projectmaker"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.2.0/project_0.2.0_darwin_amd64.tar.gz"
      sha256 "2059434998bd2220da9829e0e67c99d2146a05616d0e8b16aaf96c65bfee1365"

      define_method(:install) do
        bin.install "project"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.2.0/project_0.2.0_darwin_arm64.tar.gz"
      sha256 "34395d2b15bb75c4426630c74ea80fdf904b903e91ee1eb02cac569e90b8880c"

      define_method(:install) do
        bin.install "project"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.2.0/project_0.2.0_linux_amd64.tar.gz"
      sha256 "111ab4264634286c5705acf16aab150c222373eb1778d09ca6d371cc1ac7a42a"
      define_method(:install) do
        bin.install "project"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JadenB9/projectmaker/releases/download/v0.2.0/project_0.2.0_linux_arm64.tar.gz"
      sha256 "52e0ec87d8d44f1dc305fdeda728244bc994c7c5d71882534371606559a92588"
      define_method(:install) do
        bin.install "project"
      end
    end
  end
end
